---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart iscsi
  service:
    name: open-iscsi
    state: restarted

- name: Reboot server
  reboot:
    reboot_timeout: 60

- name: update-locale
  command: "update-locale LANG={{ system_locale }}"

- name: delete dhcp leases
  file:
    path: /var/lib/dhcp/dhclient.leases
    state: absent
  with_items:
    - /var/lib/dhcp/dhclient.leases
    - /var/lib/dhcpcd5/dhcpcd-eth0.lease
